### ISSUE TITLE
request to emit command to fix formatting on check failure

### ISSUE THREAD

**Issue by jrtom** [coveo/fmt-maven-plugin#18]
This is not super-informative:

    [ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:1.8.0:check (default) on project jung-algorithms: Found 18 non-complying files, failing build (validateOnly is true) -> [Help 1]

In particular, it would be nice if it would emit a message telling the user how to actually run the formatter, e.g.

"To fix the formatting errors, run `mvn fmt:format`."

as suggested elsewhere by @jbduncan.

Thanks for the tool!  :)

**Comment by GuiSim** [comment]
I'm super late to the party here but.. @jrtom wouldn't it make more sense to add the formatting as part of the build process and thus not have to manually run `fmt:format` ?

**Comment by jbduncan** [comment]
@GuiSim It's the same reason that we over at [Spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) make `spotlessCheck` the default task: CI is supposed to make sure that things pass an overall check, rather than automatically change code that gets checked-in.

There are at least two problems with making the formatting automatic (at least when talking about CI). Firstly, if a formatting algorithm isn't idempotent due to a bug (e.g. it requires two or more runs to reach a "final" state, or it continuously flip-flops between two equally-valid states), then CI systems will only format it properly after the second or so build run, or the the CI will continuously format the code differently.

Secondly, there will be a difference between code that gets checked in and what the code looks like after it's been checked at CI time, which is potentially very confusing.

I hope this makes at least some degree of sense. :)

**Comment by jbduncan** [comment]
Actually, it occurs to me that a formatting algorithm potentially having an idempotency bug is likely not really a problem specific for auto-formatting; I think it could easily apply to format-checking as well (but I've yet to properly think this through; wrong time of night for me to do any real thinking(!))

Apologies if I added to your confusion @GuiSim!

**Comment by GuiSim** [comment]
This makes perfect sense and I'm glad the plugin can satisfy both
approaches. Thanks for the detailed response!

On Oct 16, 2017 19:38, "Jonathan Bluett-Duncan" <notifications@github.com>
wrote:

@GuiSim <https://github.com/guisim> It's the same reason that we over at
Spotless <https://github.com/diffplug/spotless/tree/master/plugin-gradle>
make spotlessCheck the default task: CI is supposed to make sure that
things pass an overall check, rather than automatically change code that
gets checked-in.

There are at least two problems with making the formatting automatic (at
least when talking about CI). Firstly, if a formatting algorithm isn't
idempotent due to a bug (e.g. it requires two or more runs to reach a
"final" state, or it continuously flip-flops between two equally-valid
states), then CI systems will only format it properly after the second or
so build run, or the the CI will continuously format the code differently.

Secondly, there will be a difference between code that gets checked in and
what the code looks like after it's been checked at CI time, which is
potentially very confusing.

I hope this makes at least some degree of sense. :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/coveo/fmt-maven-plugin/issues/18#issuecomment-337074559>,
or mute the thread
